CREATE DATABASE virtual_lab;
USE virtual_lab;


DROP TABLE ADMINISTRATOR;
DROP TABLE SPECIFICDEVICE;
DROP TABLE GENERALDEVICE;
DROP TABLE GENERALTYPE;

CREATE TABLE GENERALTYPE(
 id INT(4) NOT NULL AUTO_INCREMENT,
 name VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE ADMINISTRATOR(
 username VARCHAR(50) PRIMARY KEY,
 password VARCHAR(100) NOT NULL
);
CREATE  TABLE GENERALDEVICE(
   id  INT(4) NOT NULL AUTO_INCREMENT,
   name VARCHAR(100) NOT NULL,
   type INT(4) NOT NULL,
   description TEXT NOT NULL,
   amount INT(4) NOT NULL,
   ports INT(3) NOT NULL,
   PRIMARY KEY(id),
    FOREIGN KEY (type) REFERENCES GENERALTYPE(id)
);
CREATE TABLE SPECIFICDEVICE(
id INT(4) PRIMARY KEY,
state VARCHAR(50) NOT NULL,
type INT(4) NOT NULL,
 FOREIGN KEY (type) REFERENCES GENERALDEVICE(id));



 INSERT INTO GENERALTYPE VALUES (2,"SWL3");
  INSERT INTO GENERALTYPE VALUES (3,"SWL2");
   INSERT INTO GENERALTYPE VALUES (4,"ROUTER");
    INSERT INTO GENERALTYPE VALUES (5,"PC");
       INSERT INTO GENERALTYPE VALUES (6,"PC2");